### ISSUE TITLE
Wrong usage of Reader::read

### ISSUE THREAD

**Issue by Xuanwo** [xiaguan/page_cache#1]
https://github.com/xiaguan/page_cache/blob/7da552b206f7bfa99c68b73c82defc666371bbbe/src/backend.rs#L17

Hi, please check the returning read size of `Reader::read` until reaching `0`. It's possible that services only read part of data.

**Comment by xiaguan** [comment]
Thank you very much for your help; I will fix the issue. I am amazed that you could check my demo in such a short amount of time 🤔

**Comment by Xuanwo** [comment]
> I am amazed that you could check my demo in such a short amount of time 🤔

I check Github `Used By` everyday :rofl:
